<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="3" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="ActiTimeTests" duration-ms="208714" started-at="2022-08-29T19:37:49 IST" finished-at="2022-08-29T19:41:18 IST">
    <groups>
    </groups>
    <test name="LoginSmokeSuite" duration-ms="208714" started-at="2022-08-29T19:37:49 IST" finished-at="2022-08-29T19:41:18 IST">
      <class name="com.actitime.tests.Login">
        <test-method status="PASS" signature="beoreTest()[pri:0, instance:com.actitime.tests.Login@fba92d3]" name="beoreTest" is-config="true" duration-ms="10" started-at="2022-08-29T19:37:50 IST" finished-at="2022-08-29T19:37:50 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beoreTest -->
        <test-method status="PASS" signature="beforeClass()[pri:0, instance:com.actitime.tests.Login@fba92d3]" name="beforeClass" is-config="true" duration-ms="0" started-at="2022-08-29T19:37:50 IST" finished-at="2022-08-29T19:37:50 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeClass -->
        <test-method status="PASS" signature="launchApplication()[pri:0, instance:com.actitime.tests.Login@fba92d3]" name="launchApplication" is-config="true" duration-ms="21049" started-at="2022-08-29T19:37:50 IST" finished-at="2022-08-29T19:38:11 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method status="PASS" signature="login_001()[pri:0, instance:com.actitime.tests.Login@fba92d3]" name="login_001" duration-ms="9185" started-at="2022-08-29T19:38:11 IST" finished-at="2022-08-29T19:38:20 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_001 -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:com.actitime.tests.Login@fba92d3]" name="closeBrowser" is-config="true" duration-ms="826" started-at="2022-08-29T19:38:20 IST" finished-at="2022-08-29T19:38:21 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method status="PASS" signature="launchApplication()[pri:0, instance:com.actitime.tests.Login@fba92d3]" name="launchApplication" is-config="true" duration-ms="50206" started-at="2022-08-29T19:38:21 IST" finished-at="2022-08-29T19:39:11 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method status="PASS" signature="login_002()[pri:0, instance:com.actitime.tests.Login@fba92d3]" name="login_002" duration-ms="47613" started-at="2022-08-29T19:39:11 IST" finished-at="2022-08-29T19:39:59 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_002 -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:com.actitime.tests.Login@fba92d3]" name="closeBrowser" is-config="true" duration-ms="778" started-at="2022-08-29T19:39:59 IST" finished-at="2022-08-29T19:39:59 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method status="PASS" signature="launchApplication()[pri:0, instance:com.actitime.tests.Login@fba92d3]" name="launchApplication" is-config="true" duration-ms="77012" started-at="2022-08-29T19:39:59 IST" finished-at="2022-08-29T19:41:16 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method status="FAIL" signature="login_003LogsTest()[pri:0, instance:com.actitime.tests.Login@fba92d3]" name="login_003LogsTest" duration-ms="2" started-at="2022-08-29T19:41:16 IST" finished-at="2022-08-29T19:41:16 IST">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The expected count of emp is not matching... expected [4] but found [3]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The expected count of emp is not matching... expected [4] but found [3]
at org.testng.Assert.fail(Assert.java:110)
at org.testng.Assert.failNotEquals(Assert.java:1413)
at org.testng.Assert.assertEqualsImpl(Assert.java:149)
at org.testng.Assert.assertEquals(Assert.java:131)
at org.testng.Assert.assertEquals(Assert.java:1240)
at com.actitime.tests.Login.login_003LogsTest(Login.java:40)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:673)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:220)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:945)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:193)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:808)
at org.testng.TestRunner.run(TestRunner.java:603)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:429)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:423)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:383)
at org.testng.SuiteRunner.run(SuiteRunner.java:326)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1249)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1169)
at org.testng.TestNG.runSuites(TestNG.java:1092)
at org.testng.TestNG.run(TestNG.java:1060)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login_003LogsTest -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:com.actitime.tests.Login@fba92d3]" name="closeBrowser" is-config="true" duration-ms="759" started-at="2022-08-29T19:41:17 IST" finished-at="2022-08-29T19:41:18 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method status="PASS" signature="afterClass()[pri:0, instance:com.actitime.tests.Login@fba92d3]" name="afterClass" is-config="true" duration-ms="0" started-at="2022-08-29T19:41:18 IST" finished-at="2022-08-29T19:41:18 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterClass -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:com.actitime.tests.Login@fba92d3]" name="afterTest" is-config="true" duration-ms="1" started-at="2022-08-29T19:41:18 IST" finished-at="2022-08-29T19:41:18 IST">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- com.actitime.tests.Login -->
    </test> <!-- LoginSmokeSuite -->
  </suite> <!-- ActiTimeTests -->
</testng-results>
